### PR TITLE
Various corrections

### PR DESCRIPTION
**Pull request by davebulaval**
# Cleaned import error, cleaned error ...
Error in dataLoader : print filename -> print(filename)
Correction of various buggy import (cPickle)
Deleted unnecessary import (re in dataLoader and many others)
(small) clean correction to class declaration and code redability

# correction of the utf-8
It appear that in some case the hashing fucking was not working.  This correction seems to work
`h.update(s) -> h.update(s.encode('utf-8'))`

# README clearer explanation and dataLoader Glove correction of binary
Bug in the pickling process (with binary was keeping the b)
Added cleaner README instructions

# REAMDE update and pickle_corpus code
Added the pickling process code
Minor error correction in README

## Cuda error
I still have cuda error. Trying to fix it. In progress.

### CODE REVIEW

**Comment by davebulaval** [comment]
Also, for the cuDNN error, it's seem like torch have some difficulties with the RTX 2080 and RNN. https://discuss.pytorch.org/t/solved-rtx-2080-ti-cudnn-error-occurs-when-loading-rnn-model-to-gpu/33880/11

**Comment by YueDongCS** [comment]
Hi, it seems that most of the errors are from python versions, we are using python 2.7 and please make sure that

**Comment by davebulaval** [comment]
With these change, the code seems to work with 3.7.

Also good to know.

**Comment by YueDongCS** [comment]
Yeah, I think we should have mentioned the python version, sorry about that. I updated the main page.

**Comment by YueDongCS** [comment]
Hi David,


First, thank you for testing our code and provides the feedbacks. I answered some of your questions and will look into the pull request.  Please feel free to contact me if you have further questions.


Best,

Yue

________________________________

**Comment by davebulaval** [comment]
Closed due to python32.7 to 3.7 not that easy.

**Pull request closed without merging**
